"""landslide_guard_models

Revision ID: ba9315b2ad0d
Revises: b12f62b93c57
Create Date: 2026-09-07 13:20:54.966695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'ba9315b2ad0d'
down_revision: Union[str, Sequence[str], None] = 'b12f62b93c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landslide_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sub_district', sa.String(length=100), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('slope_degree', sa.Float(), nullable=True),
    sa.Column('aspect', sa.Float(), nullable=True),
    sa.Column('curvature', sa.Float(), nullable=True),
    sa.Column('relief', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('vegetation_cover', sa.String(length=50), nullable=True),
    sa.Column('land_use', sa.String(length=100), nullable=True),
    sa.Column('lithology', sa.String(length=100), nullable=True),
    sa.Column('risk_baseline', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_sensors', sa.Boolean(), nullable=True),
    sa.Column('monitoring_priority', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_landslide_zones_centroid', 'landslide_zones', ['centroid'], unique=False, postgresql_using='gist')
    # op.create_index('idx_landslide_zones_geometry', 'landslide_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_landslide_zones_district'), 'landslide_zones', ['district'], unique=False)
    op.create_index(op.f('ix_landslide_zones_id'), 'landslide_zones', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_zones_name'), 'landslide_zones', ['name'], unique=False)
    op.create_index(op.f('ix_landslide_zones_state'), 'landslide_zones', ['state'], unique=False)
    op.create_index(op.f('ix_landslide_zones_zone_code'), 'landslide_zones', ['zone_code'], unique=True)
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('road_type', sa.String(length=30), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('start_point', sa.String(length=200), nullable=True),
    sa.Column('end_point', sa.String(length=200), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('blockage_description', sa.Text(), nullable=True),
    sa.Column('estimated_clearance_hours', sa.Float(), nullable=True),
    sa.Column('alternate_route', sa.String(length=500), nullable=True),
    sa.Column('last_status_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_roads_geometry', 'roads', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False)
    op.create_index(op.f('ix_roads_name'), 'roads', ['name'], unique=False)
    op.create_index(op.f('ix_roads_road_type'), 'roads', ['road_type'], unique=False)
    op.create_index(op.f('ix_roads_state'), 'roads', ['state'], unique=False)
    op.create_index(op.f('ix_roads_status'), 'roads', ['status'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('severity_estimate', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('address_text', sa.String(length=500), nullable=True),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('media_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('linked_event_id', sa.Integer(), nullable=True),
    sa.Column('client_report_id', sa.String(length=100), nullable=True),
    sa.Column('submitted_offline', sa.Boolean(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_event_id'], ['landslide_events.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_report_id')
    )
    # op.create_index('idx_citizen_reports_location', 'citizen_reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_citizen_reports_id'), 'citizen_reports', ['id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_report_type'), 'citizen_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_citizen_reports_status'), 'citizen_reports', ['status'], unique=False)
    op.create_index(op.f('ix_citizen_reports_submitted_at'), 'citizen_reports', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_citizen_reports_user_id'), 'citizen_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_citizen_reports_zone_id'), 'citizen_reports', ['zone_id'], unique=False)
    op.create_table('critical_infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('infra_type', sa.String(length=50), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('risk_exposure_level', sa.String(length=20), nullable=True),
    sa.Column('last_inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_critical_infrastructure_location', 'critical_infrastructure', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_critical_infrastructure_id'), 'critical_infrastructure', ['id'], unique=False)
    op.create_index(op.f('ix_critical_infrastructure_infra_type'), 'critical_infrastructure', ['infra_type'], unique=False)
    op.create_index(op.f('ix_critical_infrastructure_name'), 'critical_infrastructure', ['name'], unique=False)
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cause', sa.String(length=200), nullable=True),
    sa.Column('casualties', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.Integer(), nullable=True),
    sa.Column('houses_damaged', sa.Integer(), nullable=True),
    sa.Column('infrastructure_damage', sa.Text(), nullable=True),
    sa.Column('road_blocked', sa.Boolean(), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('estimated_clearance_hours', sa.Float(), nullable=True),
    sa.Column('volume_cubic_m', sa.Float(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('source_report_id', sa.Integer(), nullable=True),
    sa.Column('weather_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['citizen_reports.id'], use_alter=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_landslide_events_location', 'landslide_events', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_landslide_events_district'), 'landslide_events', ['district'], unique=False)
    op.create_index(op.f('ix_landslide_events_event_type'), 'landslide_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_landslide_events_id'), 'landslide_events', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_events_occurred_at'), 'landslide_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_landslide_events_severity'), 'landslide_events', ['severity'], unique=False)
    op.create_index(op.f('ix_landslide_events_state'), 'landslide_events', ['state'], unique=False)
    op.create_index(op.f('ix_landslide_events_zone_id'), 'landslide_events', ['zone_id'], unique=False)
    op.create_table('rainfall_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('intensity', sa.String(length=30), nullable=True),
    sa.Column('cumulative_24h', sa.Float(), nullable=True),
    sa.Column('cumulative_48h', sa.Float(), nullable=True),
    sa.Column('cumulative_72h', sa.Float(), nullable=True),
    sa.Column('cumulative_7d', sa.Float(), nullable=True),
    sa.Column('antecedent_rainfall_index', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainfall_data_district'), 'rainfall_data', ['district'], unique=False)
    op.create_index(op.f('ix_rainfall_data_id'), 'rainfall_data', ['id'], unique=False)
    op.create_index(op.f('ix_rainfall_data_recorded_at'), 'rainfall_data', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_rainfall_data_state'), 'rainfall_data', ['state'], unique=False)
    op.create_index(op.f('ix_rainfall_data_station_name'), 'rainfall_data', ['station_name'], unique=False)
    op.create_index(op.f('ix_rainfall_data_zone_id'), 'rainfall_data', ['zone_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_window_hours', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('previous_risk_level', sa.String(length=20), nullable=True),
    sa.Column('level_changed', sa.Integer(), nullable=True),
    sa.Column('alert_triggered', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_assessed_at'), 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_zone_id'), 'risk_assessments', ['zone_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Integer(), nullable=True),
    sa.Column('reading_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_sensor_readings_location', 'sensor_readings', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_reading_at'), 'sensor_readings', ['reading_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_type'), 'sensor_readings', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_sensor_readings_zone_id'), 'sensor_readings', ['zone_id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_local', sa.String(length=200), nullable=True),
    sa.Column('village_code', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('panchayat', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('households', sa.Integer(), nullable=True),
    sa.Column('nearest_road_id', sa.Integer(), nullable=True),
    sa.Column('distance_to_road_km', sa.Float(), nullable=True),
    sa.Column('nearest_hospital_km', sa.Float(), nullable=True),
    sa.Column('nearest_town', sa.String(length=200), nullable=True),
    sa.Column('accessibility_status', sa.String(length=30), nullable=True),
    sa.Column('vulnerable', sa.Boolean(), nullable=True),
    sa.Column('risk_exposure', sa.String(length=20), nullable=True),
    sa.Column('has_shelter', sa.Boolean(), nullable=True),
    sa.Column('shelter_capacity', sa.Integer(), nullable=True),
    sa.Column('has_mobile_network', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nearest_road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_code')
    )
    # op.create_index('idx_villages_location', 'villages', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_villages_district'), 'villages', ['district'], unique=False)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_index(op.f('ix_villages_state'), 'villages', ['state'], unique=False)
    op.create_table('landslide_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_district', sa.String(length=100), nullable=True),
    sa.Column('target_state', sa.String(length=100), nullable=True),
    sa.Column('recipients_count', sa.Integer(), nullable=True),
    sa.Column('sms_sent_count', sa.Integer(), nullable=True),
    sa.Column('push_sent_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to', sa.String(length=30), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('evacuation_required', sa.Boolean(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['landslide_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landslide_alerts_alert_type'), 'landslide_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_landslide_alerts_id'), 'landslide_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_landslide_alerts_issued_at'), 'landslide_alerts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_landslide_alerts_risk_level'), 'landslide_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_landslide_alerts_status'), 'landslide_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_landslide_alerts_zone_id'), 'landslide_alerts', ['zone_id'], unique=False)
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.add_column('alert_subscriptions', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.alter_column('alert_subscriptions', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'alert_subscriptions', 'landslide_zones', ['zone_id'], ['id'])
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('sms_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('push_alerts_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # op.create_index('idx_users_location', 'users', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_users_district'), 'users', ['district'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_district'), table_name='users')
    op.drop_index('idx_users_location', table_name='users', postgresql_using='gist')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'state')
    op.drop_column('users', 'district')
    op.drop_column('users', 'location')
    op.drop_column('users', 'push_alerts_enabled')
    op.drop_column('users', 'sms_alerts_enabled')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'alert_subscriptions', type_='foreignkey')
    op.alter_column('alert_subscriptions', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('alert_subscriptions', 'zone_id')
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.drop_index(op.f('ix_landslide_alerts_zone_id'), table_name='landslide_alerts')
    op.drop_index(op.f('ix_landslide_alerts_status'), table_name='landslide_alerts')
    op.drop_index(op.f('ix_landslide_alerts_risk_level'), table_name='landslide_alerts')
    op.drop_index(op.f('ix_landslide_alerts_issued_at'), table_name='landslide_alerts')
    op.drop_index(op.f('ix_landslide_alerts_id'), table_name='landslide_alerts')
    op.drop_index(op.f('ix_landslide_alerts_alert_type'), table_name='landslide_alerts')
    op.drop_table('landslide_alerts')
    op.drop_index(op.f('ix_villages_state'), table_name='villages')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_district'), table_name='villages')
    op.drop_index('idx_villages_location', table_name='villages', postgresql_using='gist')
    op.drop_table('villages')
    op.drop_index(op.f('ix_sensor_readings_zone_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_type'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_reading_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_location', table_name='sensor_readings', postgresql_using='gist')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_risk_assessments_zone_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessed_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_rainfall_data_zone_id'), table_name='rainfall_data')
    op.drop_index(op.f('ix_rainfall_data_station_name'), table_name='rainfall_data')
    op.drop_index(op.f('ix_rainfall_data_state'), table_name='rainfall_data')
    op.drop_index(op.f('ix_rainfall_data_recorded_at'), table_name='rainfall_data')
    op.drop_index(op.f('ix_rainfall_data_id'), table_name='rainfall_data')
    op.drop_index(op.f('ix_rainfall_data_district'), table_name='rainfall_data')
    op.drop_table('rainfall_data')
    op.drop_index(op.f('ix_landslide_events_zone_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_state'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_severity'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_occurred_at'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_id'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_event_type'), table_name='landslide_events')
    op.drop_index(op.f('ix_landslide_events_district'), table_name='landslide_events')
    op.drop_index('idx_landslide_events_location', table_name='landslide_events', postgresql_using='gist')
    op.drop_table('landslide_events')
    op.drop_index(op.f('ix_critical_infrastructure_name'), table_name='critical_infrastructure')
    op.drop_index(op.f('ix_critical_infrastructure_infra_type'), table_name='critical_infrastructure')
    op.drop_index(op.f('ix_critical_infrastructure_id'), table_name='critical_infrastructure')
    op.drop_index('idx_critical_infrastructure_location', table_name='critical_infrastructure', postgresql_using='gist')
    op.drop_table('critical_infrastructure')
    op.drop_index(op.f('ix_citizen_reports_zone_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_user_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_submitted_at'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_status'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_report_type'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_id'), table_name='citizen_reports')
    op.drop_index('idx_citizen_reports_location', table_name='citizen_reports', postgresql_using='gist')
    op.drop_table('citizen_reports')
    op.drop_index(op.f('ix_roads_status'), table_name='roads')
    op.drop_index(op.f('ix_roads_state'), table_name='roads')
    op.drop_index(op.f('ix_roads_road_type'), table_name='roads')
    op.drop_index(op.f('ix_roads_name'), table_name='roads')
    op.drop_index(op.f('ix_roads_id'), table_name='roads')
    op.drop_index('idx_roads_geometry', table_name='roads', postgresql_using='gist')
    op.drop_table('roads')
    op.drop_index(op.f('ix_landslide_zones_zone_code'), table_name='landslide_zones')
    op.drop_index(op.f('ix_landslide_zones_state'), table_name='landslide_zones')
    op.drop_index(op.f('ix_landslide_zones_name'), table_name='landslide_zones')
    op.drop_index(op.f('ix_landslide_zones_id'), table_name='landslide_zones')
    op.drop_index(op.f('ix_landslide_zones_district'), table_name='landslide_zones')
    op.drop_index('idx_landslide_zones_geometry', table_name='landslide_zones', postgresql_using='gist')
    op.drop_index('idx_landslide_zones_centroid', table_name='landslide_zones', postgresql_using='gist')
    op.drop_table('landslide_zones')
    # ### end Alembic commands ###
